name: doctor
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.17
  firebase_database: ^9.0.15
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  # flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/logo.png
    - assets/images/dhaka.jpeg
    - assets/images/khulna.jpeg
    - assets/images/barishal.jpeg
    - assets/images/chittagong.jpeg
    - assets/images/mymensingh.jpeg
    - assets/images/rajshahi.jpeg
    - assets/images/rangpur.jpeg
    - assets/images/sylhet.jpeg
    - assets/images/medical.png
    - assets/images/doctor.jpg
    

  